<%@ Page Language="C#" %>
<!DOCTYPE html>
<head>
    <title>The Nest
    </title>

    <link rel="stylesheet" href="css/style.css" type="text/css" >
    <link rel="icon" href="images/OwlFavicon1.png" type="image/x-icon">
	
</head>

<body>

<header>
<left>
<p><br/>
<a href="./">CutieOwl</a><br/>
</p>
</left>
</header>

<div id="container">

<navcontainer>
<!--#include file ="menu.inc" -->
</navcontainer>

<contents>

